export const userManagementConfig = {
  tableLabel: [
    {
      value: 'Title',
      key: 'title',
    },
    {
      value: 'First name',
      key: 'firstName',
    },
    {
      value: 'Last name',
      key: 'lastName',
    },
    {
      value: 'Middle name',
      key: 'middleName',
    },
    {
      value: 'Email address',
      key: 'email',
    },
    {
      value: 'Gender',
      key: 'gender',
    },
    {
      value: 'Phone number',
      key: 'phoneNumber',
    },
    {
      value: 'Date of birth',
      key: 'dateOfBirth',
    },
    { value: 'Role', key: 'role' },
  ],
  gridLable: [],
  data: [
    {
      title: 'Mr',
      id: '123451',
      firstName: 'Thomas',
      portrait:
        'https://widgetwhats.com/app/uploads/2019/11/free-profile-photo-whatsapp-1.png',
      lastName: 'King',
      middleName: 'Marius',
      email: 'thomasking@gmail.com',
      gender: 'Male',
      phoneNumber: '+8078774547',
      dateOfBirth: '1988/04/10',
      role: [
        {
          name: 'Owner',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: false,
          descriptionKey: 'userManageMentRoleDescriptionKey1',
        },
      ],
      fullName: 'Thomas King',
      active: true,
      locked: false,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '123452',
      firstName: 'Rose',
      portrait: '',
      lastName: 'King',
      middleName: 'J',
      email: 'roseking222@gmail.com',
      gender: 'Female',
      phoneNumber: '+8078778547',
      dateOfBirth: '1948/04/10',
      role: [
        {
          name: 'Agent',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey2',
        },
      ],
      fullName: 'Rose King',
      active: true,
      locked: true,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '123453',
      firstName: 'Grace',
      portrait: '',
      lastName: 'Cole',
      middleName: 'Dude',
      email: 'graciedude@yahoo.com',
      gender: 'Female',
      phoneNumber: '+234785964752',
      dateOfBirth: '1958/01/14',
      role: [
        {
          name: 'Administrator',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey3',
        },
      ],
      fullName: 'Grace Cole',
      active: true,
      locked: false,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mr',
      id: '123454',
      firstName: 'Jade',
      portrait:
        'https://widgetwhats.com/app/uploads/2019/11/free-profile-photo-whatsapp-3-300x300.png',
      lastName: 'Smith',
      middleName: 'Jaararda',
      email: 'ypuknowjade@gmail.com',
      gender: 'Male',
      phoneNumber: '+8078778547',
      dateOfBirth: '1948/10/18',
      role: [
        {
          name: 'Agent',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey2',
        },
      ],
      fullName: 'Jade Smith',
      active: false,
      locked: false,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '123455',
      firstName: 'Grace',
      portrait: '',
      lastName: 'Cole',
      middleName: 'Dude',
      email: 'graciedude@yahoo.com',
      gender: 'Female',
      phoneNumber: '+234785964752',
      dateOfBirth: '1958/01/14',
      role: [
        {
          name: 'Administrator',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey3',
        },
      ],
      fullName: 'Grace Cole',
      active: true,
      locked: true,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '123456',
      firstName: 'Rose',
      portrait:
        'https://widgetwhats.com/app/uploads/2019/11/free-profile-photo-whatsapp-2.png',
      lastName: 'King',
      middleName: 'J',
      email: 'roseking222@gmail.com',
      gender: 'Female',
      phoneNumber: '+8078778547',
      dateOfBirth: '1948/04/10',
      role: [
        {
          name: 'Administrator',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey3',
        },
      ],
      fullName: 'Rose King',
      active: true,
      locked: true,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mr',
      id: '123457',
      firstName: 'Jade',
      portrait: '',
      lastName: 'Smith',
      middleName: 'Jaararda',
      email: 'ypuknowjade@gmail.com',
      gender: 'Male',
      phoneNumber: '+8078778547',
      dateOfBirth: '1948/10/18',
      role: [
        {
          name: 'Agent',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey2',
        },
      ],
      fullName: 'Jade Smith',
      active: false,
      locked: true,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '123458',
      firstName: 'Grace',
      portrait: '',
      lastName: 'Cole',
      middleName: 'Dude',
      email: 'graciedude@yahoo.com',
      gender: 'Female',
      phoneNumber: '+234785964752',
      dateOfBirth: '',
      role: [
        {
          name: 'Administrator',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey3',
        },
      ],
      fullName: 'Grace Cole',
      active: true,
      locked: false,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '123495',
      firstName: 'Grace',
      portrait:
        'https://widgetwhats.com/app/uploads/2019/11/free-profile-photo-whatsapp-3-300x300.png',
      lastName: 'Cole',
      middleName: 'Dude',
      email: 'graciedude@yahoo.com',
      gender: 'Female',
      phoneNumber: '+234785964752',
      dateOfBirth: '1958/01/14',
      role: [
        {
          name: 'Administrator',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey3',
        },
      ],
      fullName: 'Grace Cole',
      active: true,
      locked: false,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mr',
      id: '123435',
      firstName: 'Jade',
      portrait: '',
      lastName: 'Smith',
      middleName: 'Jaararda',
      email: 'ypuknowjade@gmail.com',
      gender: 'Male',
      phoneNumber: '+8078778547',
      dateOfBirth: '1948/10/18',
      role: [],
      fullName: 'Jade Smith',
      active: true,
      locked: false,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '12349533',
      firstName: 'Grace',
      portrait:
        'https://widgetwhats.com/app/uploads/2019/11/free-profile-photo-whatsapp-3-300x300.png',
      lastName: 'Cole',
      middleName: 'Dude',
      email: 'graciedude@yahoo.com',
      gender: 'Female',
      phoneNumber: '+234785964752',
      dateOfBirth: '1958/01/14',
      role: [
        {
          name: 'Administrator',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey3',
        },
      ],
      fullName: 'Grace Cole',
      active: true,
      locked: false,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '123453332',
      firstName: 'Rose',
      portrait: '',
      lastName: 'King',
      middleName: 'J',
      email: 'roseking222@gmail.com',
      gender: 'Female',
      phoneNumber: '+8078778547',
      dateOfBirth: '1948/04/10',
      role: [
        {
          name: 'Agent',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey2',
        },
      ],
      fullName: 'Rose King',
      active: true,
      locked: true,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '1234333353',
      firstName: 'Grace',
      portrait: '',
      lastName: 'Cole',
      middleName: 'Dude',
      email: 'graciedude@yahoo.com',
      gender: 'Female',
      phoneNumber: '+234785964752',
      dateOfBirth: '1958/01/14',
      role: [
        {
          name: 'Administrator',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey3',
        },
      ],
      fullName: 'Grace Cole',
      active: true,
      locked: false,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mr',
      id: '123333454',
      firstName: 'Jade',
      portrait:
        'https://widgetwhats.com/app/uploads/2019/11/free-profile-photo-whatsapp-3-300x300.png',
      lastName: 'Smith',
      middleName: 'Jaararda',
      email: 'ypuknowjade@gmail.com',
      gender: 'Male',
      phoneNumber: '+8078778547',
      dateOfBirth: '1948/10/18',
      role: [
        {
          name: 'Agent',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey2',
        },
      ],
      fullName: 'Jade Smith',
      active: false,
      locked: false,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '1234553333',
      firstName: 'Grace',
      portrait: '',
      lastName: 'Cole',
      middleName: 'Dude',
      email: 'graciedude@yahoo.com',
      gender: 'Female',
      phoneNumber: '+234785964752',
      dateOfBirth: '1958/01/14',
      role: [
        {
          name: 'Administrator',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey3',
        },
      ],
      fullName: 'Grace Cole',
      active: true,
      locked: true,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
    {
      title: 'Mrs',
      id: '1233333433356',
      firstName: 'Rose',
      portrait:
        'https://widgetwhats.com/app/uploads/2019/11/free-profile-photo-whatsapp-2.png',
      lastName: 'King',
      middleName: 'J',
      email: 'roseking222@gmail.com',
      gender: 'Female',
      phoneNumber: '+8078778547',
      dateOfBirth: '1948/04/10',
      role: [
        {
          name: 'Administrator',
          description:
            'This user has access to verify both IDs and their bearers using the iDQR verification app',
          configurable: true,
          descriptionKey: 'userManageMentRoleDescriptionKey3',
        },
      ],
      fullName: 'Rose King',
      active: true,
      locked: true,
      createDate: '22/06/2019',
      createTime: '09:03 am',
    },
  ],
  roles: [
    {
      name: 'Owner',
      description:
        'This user has access to verify both IDs and their bearers using the iDQR verification app',
      configurable: false,
      descriptionKey: 'userManageMentRoleDescriptionKey1',
    },
    {
      name: 'Agent',
      description:
        'This user has access to verify both IDs and their bearers using the iDQR verification app',
      configurable: true,
      descriptionKey: 'userManageMentRoleDescriptionKey2',
    },
    {
      name: 'Administrator',
      description:
        'This user has access to verify both IDs and their bearers using the iDQR verification app',
      configurable: true,
      descriptionKey: 'userManageMentRoleDescriptionKey3',
    },
  ],
  metadata: { total: 16, active: 16, inactive: 16 },
  viewUserLabel: [
    {
      value: 'Date Created',
      key: 'dateCreated',
    },
    {
      value: 'Time Created',
      key: 'timeCreated',
    },
    {
      value: 'Title',
      key: 'title',
    },
    {
      value: 'First name',
      key: 'firstName',
    },
    {
      value: 'Last name',
      key: 'lastName',
    },
    {
      value: 'Middle name',
      key: 'middleName',
    },
    {
      value: 'Email address',
      key: 'email',
    },
    {
      value: 'Phone number',
      key: 'phoneNumber',
    },
    {
      value: 'Gender',
      key: 'gender',
    },
    {
      value: 'Date of birth',
      key: 'dateOfBirth',
    },
    { value: 'Role', key: 'role' },
  ],
};
